notify setup modded

diff --git a/scripts/manage-snapshot-ukis b/scripts/manage-snapshot-ukis
--- a/scripts/manage-snapshot-ukis
+++ b/scripts/manage-snapshot-ukis
@@ -57,24 +57,24 @@ notify() {
     local title="$2"
     local message="$3"
     local icon="${4:-$NOTIFY_ICON_INFO}"
-REALUSER="${SUDO_USER:-$USER}"
 
     if [ "$NOTIFY_ENABLED" != "true" ]; then
         return 0
     fi
 
-      # try notify-send (works on most Linux DEs)
- #   if command -v notify-send &>/dev/null; then
- #  sudo -u "$REALUSER" DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send -u "$urgency" -i "$icon" -a "$APP_NAME" "$title" "$message" 2>/dev/null || true
- #       return 0
- #   fi
+       # try notify-send (works on most Linux DEs)
+     if command -v notify-send &>/dev/null; then
+        sudo -u $(id -u -n 1000)  DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send -u "$urgency" -i "$icon" -a "$APP_NAME" "$title" "$message" 2>/dev/null || true
+       return 0
+    fi
 
     # try wall (should work everywhere)
      if command -v wall &>/dev/null; then
     wall -n "$message" 2>/dev/null || true
         return 0
     fi
-# exit silently if not found
+
+# no notification tool available - silent fail
        return 0
 }
 
